name: lru
description: A feature-rich Least Recently Used (LRU) cache implementation in Dart with advanced options and event handling.
version: 1.0.0
homepage: https://github.com/lollipopkit/lru.dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.24.0
  lints: ^5.1.1
